### ISSUE TITLE
Other impostors cant kill

### ISSUE THREAD

**Issue by CyanTheCyantist** [g0aty/SickoMenu#1]
When I'm hosting, for some reason I'm the only one who can kill. I've tried everything to see what to do to fix it and cant figure it out. Can anyone help me please?

**Comment by g0aty** [comment]
This seems to be an issue with PlayerControl_CmdCheckMurder, as the host receives this and should execute a murder for the player, but due to a glitch with the current hook this does not go through and fails to murder the player.
Hopefully, this issue will be fixed in the next update!

**Comment by g0aty** [comment]
Fixed in [the new update](https://github.com/g0aty/SickoMenu/commit/6d67884948e191e6eda047ff64eecdcff52545e3)

**Comment by CyanTheCyantist** [comment]
ok nice!
