### ISSUE TITLE
Safe Mode is bugged

### ISSUE THREAD

**Issue by Jannatul89sInGithub** [g0aty/SickoMenu#101]
safe mode aint working. anticheat kicks me out whenever i kill everyone/crewmates/impostors or just a individual person using the menu. also, whenever i kill someone as a crewmate then get voted out, anticheat kicks me out.

**Comment by Jannatul89sInGithub** [comment]
also wanna mention when i updated back to 3.5, safe mode worked fine

**Comment by terrifyiedz** [comment]
Don't turn off host anti cheat, because anything you do will get you kicked, leave on safe mode and leave on host anti cheat, and redownload 3.5.1

**Comment by Jannatul89sInGithub** [comment]
ok what is host anti cheat? i've never heard of that. i don't see that in the menu

**Comment by Jannatul89sInGithub** [comment]
> Don't turn off host anti cheat, because anything you do will get you kicked, leave on safe mode and leave on host anti cheat, and redownload 3.5.1

so basically in 3.5, i have to turn off host anti cheat, then put 3.5.1 in the among us folder. right?

**Comment by terrifyiedz** [comment]
No remove the old SickoMenu v3.5 just put v3.5.1 in your among folder and open amoung. Dont turn of host anti cheat, because then you'll keep getting kicked, if you need further assistance ping @terrifyiedz  in the discord server in the support channel

**Comment by Jannatul89sInGithub** [comment]
> No remove the old SickoMenu v3.5 just put v3.5.1 in your among folder and open among us . Dont turn of host anti cheat, because then you'll keep getting kicked, if you need further assistance ping @terrifyiedz in the discord server in the support channel

yo can you give me your correct discord username?
