### ISSUE TITLE
how do i even download this

### ISSUE THREAD

**Issue by MrBeast661** [g0aty/SickoMenu#102]
i cant download this beacuse if i click the code and download zip i cant enable it theres no exe file and if i download the release sasme i get 3 files which doesnt do anything

**Comment by terrifyiedz** [comment]
There is you just need to turn off antivirus , when you download the release.zip extract then open it in, in the folder take "Version.dll" and go to steam or where you can access your among us files and put it in there. In steam go to among us press the circle with he blocky hinges next to it press browse files and put it in there.   If you need further assistance go to the discord and ping @terrifyiedz

**Comment by Corvex2** [comment]
1. Download release.zip
2. extract files
3. copy version.dll
4. paste version.dll in among us game directory (right click among us on steam>manage>browse local files
5. click play
6. ruin peoples fun

**Comment by RobloxGabriel1** [comment]
simpler way:
install release.zip or debug.zip
go inside the .zip file
take the version.dll file and insert it in among us file.
open the game and start trolling

**Comment by Corvex2** [comment]
@RobloxGabriel1  Yeah that works but some people dont know where to find the game files
