### ISSUE TITLE
cant kill as non-impostor with unlock kill button 

### ISSUE THREAD

**Issue by Reycko** [g0aty/SickoMenu#103]
you just cant kill. i know this is a bad issue due to lack of comments but idrk what to put. theres a bug or smth. the button is always gray but you can kill with autokill or the kill all crewmates/impostors buttons

**Comment by terrifyiedz** [comment]
Go to releases channel in the discord v3.5.2 has released

**Comment by terrifyiedz** [comment]
And make sure you don't have host anti cheat off, keep it on at all times.

**Comment by Reycko** [comment]
> Go to releases channel in the discord v3.5.2 has released

i know

> And make sure you don't have host anti cheat off, keep it on at all times.

yeah dw i saw its bad, but it happens even when im not host

**Comment by Reycko** [comment]
likely related to https://discord.com/channels/1198112143120277524/1258901349416833044/1258901349416833044

> when unlock kill button is enabled, you cannot select any crewmates or impostors even with "kill other impostors" enabled. A workaround for this can be done by setting yourself as impostor with the fake role.

**Comment by terrifyiedz** [comment]
In that but report he's mainly talking about just using the "unlock kill button " in general if you use that actual menu to kill it always works, if you need further assistance or help with any inquiries just dm @terrifyiedz  on discord
