### ISSUE TITLE
Freeplay mode issue.

### ISSUE THREAD

**Issue by RobloxGabriel1** [g0aty/SickoMenu#109]
Whenever I try to access practice, for some reason, it just glitches and crashes Among Us. I am using SickoMenu v3.5.2 and the latest version of Among Us. Can you please fix this issue?

**Comment by Reycko** [comment]
known issue. also do you mean 3.5.2? 3.2 is very old

**Comment by RobloxGabriel1** [comment]
oops i meant 3.5.2

**Comment by crzylemon** [comment]
same thing happened to me with local mode

**Comment by g0aty** [comment]
Fixed!
