### ISSUE TITLE
Add Fortegreen as selectable color

### ISSUE THREAD

**Issue by heavyutils** [g0aty/SickoMenu#13]
And in general just let power users do their thing by selecting custom IDs for everything, color, platform, etc.

**Comment by g0aty** [comment]
Pretty sure you can already select fortegreen when hosting, when you're not the game just kicks you.
Platform can be spoofed in Settings > Spoofing.

**Comment by heavyutils** [comment]
Lol how did I miss fortegreen, just hopped back on and found it. But platform UNKNOWN can't be selected with this mod
