### ISSUE TITLE
add anticheat bypass + ToH Support

### ISSUE THREAD

**Issue by VixenSugo** [g0aty/SickoMenu#133]
can you make a bypass for anticheat tools (for example [this project](https://github.com/Night-GUA/YuAntiCheat))

pls add town of us roles.
When i inject the mod menu dll into the among us toh process by injector, the values ​​are hidden and seem to be encrypted
And due to encryption or the absence of role names, the among us closes after running your mod menu. Even if the toh roles are not added and only crew or imp are marked with red and white color (in players section and esp color) it's enough. Only if it's possible to do something so that when using your mod menu in the toh roles version, the processing among us does not close

[toh project](https://github.com/0xDrMoe/TownofHost-Enhanced)

**Comment by g0aty** [comment]
Anticheat bypassing is not planned. The disclaimer clearly says to "use the menu at your own risk".
