### ISSUE TITLE
Server list blank and menu doesn't show up when pressing del for version dll

### ISSUE THREAD

**Issue by MachinePlaygroundPeopleMachine** [g0aty/SickoMenu#135]
In version version dll 3.6, the server list is blank (no servers show up) and pressing del doesn't activate the menu. I pasted the version dll file into my among us directory, but not only did the cheat menu not work, I can't play on any servers as the server list is blank and empty.

**Comment by g0aty** [comment]
Works as intended, turn off +25 mode in the debug tab and check your drivers.
