### ISSUE TITLE
(HOW I FIX THIS?) Unable to retrieve IDXGISwapChain::Present method

### ISSUE THREAD

**Issue by raddanzin** [g0aty/SickoMenu#136]
[ERROR - Sicko - DetourInitilization] Unable to retrieve IDXGISwapChain::Present method

**Comment by heavyutils** [comment]
DONT use version.dll

**Comment by raddanzin** [comment]
> DONT use version.dll

sure, but even i inject sickomenu.dll i cant use, so what i do?

**Comment by raddanzin** [comment]
> Maybe this is an issue with your direct X version. ![Screenshot_20240802-075415](https://private-user-images.githubusercontent.com/177276335/354585519-c57e68c5-db87-469b-9429-9fa5647a5f1c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI2MTc1MzksIm5iZiI6MTcyMjYxNzIzOSwicGF0aCI6Ii8xNzcyNzYzMzUvMzU0NTg1NTE5LWM1N2U2OGM1LWRiODctNDY5Yi05NDI5LTlmYTU2NDdhNWYxYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwMlQxNjQ3MTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mZWYxYTc0ZTYyMzc1N2NiZjhlNDE0OWE5NzNhNDQwZjBkOTg5MTY5ZjY1NmI0MWQzYzZmYTI1ZmE2MjVkOGIyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.vtHTmUdmeFFS_qnLFDhXDKrF_ecNTPwh43fZCyFnoy0)

i guess not, cause i update my windows yesterday, and all its fine

**Comment by raddanzin** [comment]
> What about your drivers? The graphics driver is important

all drivers are updated too, thats the worst...causa idk where is problem (this error happens on AUM too)

**Comment by raddanzin** [comment]
i've been searching and i saw that was a programation/hook line, but idk how fix

look this example on AUM hooks: https://github.com/BitCrackers/AmongUsMenu/blob/main/hooks/_hooks.cpp

goaty made Sicko, if he could point the error...

**Comment by g0aty** [comment]
> i've been searching and i saw that was a programation/hook line, but idk how fix
> 
> 
> 
> look this example on AUM hooks: https://github.com/BitCrackers/AmongUsMenu/blob/main/hooks/_hooks.cpp
> 
> 
> 
> goaty made Sicko, if he could point the error...

Slight correction: I forked the menu from AUM itself, the error can be fixed by updating your drivers.
