### ISSUE TITLE
Anti-kick

### ISSUE THREAD

**Issue by heavyutils** [g0aty/SickoMenu#139]
Do so you won't get disconnected from your own lobby if you get votekicked

**Comment by g0aty** [comment]
Planned for expanded host tab!

**Comment by g0aty** [comment]
Indeed!

**Comment by g0aty** [comment]
I've tested it out on the latest release and it seems to work well.

**Comment by redphantom1000** [comment]
Wait that's a thing now? Is there a way to toggle it?

**Comment by g0aty** [comment]
It is enabled by default as host.
