### ISSUE TITLE
Windows 11 not supported version?

### ISSUE THREAD

**Issue by KidTechnical** [g0aty/SickoMenu#140]
Self-explanatory. When I launch SickoMenu I get a "version not supported" error.

**Comment by g0aty** [comment]
> Self-explanatory. When I launch SickoMenu I get a "version not supported" error.

Interesting, try updating your drivers.

**Comment by zoukou** [comment]
> > Self-explanatory. When I launch SickoMenu I get a "version not supported" error.
> 
> Interesting, try updating your drivers.

What driver?
