### ISSUE TITLE
Game "Among Us" Crashes

### ISSUE THREAD

**Issue by Ismail1295** [g0aty/SickoMenu#141]
The cheat crashes, I don’t know what to do. It crashes in 2-3 minutes. Among us itch.io.I tried other cheats, they don’t crash, but they have few functions, your cheat is the best, it’s a pity it just crashes :(

**Comment by Ismail1295** [comment]
Когда Чит выключен?Я сейчас проверю

**Comment by Ismail1295** [comment]
> происходит ли сбой, когда они все отключены?

I'll check now

**Comment by Ismail1295** [comment]
When I use the cheat functions it crashes, but if I don’t use it it doesn’t crash.

**Comment by g0aty** [comment]
Use v3.5.2 instead for stability.

**Comment by Ismail1295** [comment]
Will the functions remain and will it also be suitable for the current version?

**Comment by g0aty** [comment]
Most functions, with the exceptions of hiding watermark and killing while vanished will still remain.

**Comment by Ismail1295** [comment]
> Большинство функций, за исключением скрытия водяного знака и удаления при исчезновении, по-прежнему останутся.

Thanks, I'll check and write later

**Comment by Ismail1295** [comment]
> Большинство функций, за исключением скрытия водяного знака и удаления при исчезновении, по-прежнему останутся.

I downloaded version 3.5.2, but it still crashes :(

**Comment by Ismail1295** [comment]
The drivers are all updated, I installed the version this way: I copied the file Version In the folder with among us.

**Comment by Ismail1295** [comment]
I have the first ac not from Steam and not from Epic Games

**Comment by Ismail1295** [comment]
Yes, I have Discord, here ismailkasumov

**Comment by Ismail1295** [comment]
What kind of Discord is there?

**Comment by Ismail1295** [comment]
I logged into Discord, I don’t know what to do next

**Comment by Ismail1295** [comment]
My Discord doesn't work well, is there another way?

**Comment by Ismail1295** [comment]
I wrote in discord in the bug reports tab with the tag crash reports
