### ISSUE TITLE
не работаетт чит

### ISSUE THREAD

**Issue by BAPotat0** [g0aty/SickoMenu#144]
не работает чит на среди нас .стим версия нажимал на горячие клавиши и с fn тоже

**Comment by felix-yata** [comment]
Зайди на Дискорд сервер проекта, там тебе помогут с большей вероятностью чем здесь. И ещё будь добр общаться на английском, если знаешь его хоть чуть-чуть) Само меню работает прекрасно, скорее всего у тебя просто кривые руки или что-то с системой.
