### ISSUE TITLE
More readable colors?

### ISSUE THREAD

**Issue by pep0w** [g0aty/SickoMenu#147]
The roles change the color to the name. And are unreadable.
For example, noisemaker is purple and is super hard to read, other roles are hard to read too.
I suggest having them like so:
Crewmate: white
crewmate role: light blue (regardless which role it is)
impostor (with or without role): red

also the radar make it more visible who is the impostor.

**Comment by redphantom1000** [comment]
malum menu does this when reveal roles is turned on. this looks like a good idea

**Comment by g0aty** [comment]
Made colors more readable in v3.7!
