### ISSUE TITLE
Fake impostor getting detected and kicked

### ISSUE THREAD

**Issue by tommyBELLOFIGO** [g0aty/SickoMenu#155]
yea i get kicked whenever i kill as fake impostor

**Comment by redphantom1000** [comment]
Anticheat was updated. See the video i posted in sicko discord for more info:

https://cdn.discordapp.com/attachments/1208651420056813588/1281106014078238763/2024-09-05_00-16-57.mp4?ex=66da8273&is=66d930f3&hm=bf749279910f707ac2c845930e0d4255a23628f836f02ed0d204b5686e8ef815&

**Comment by redphantom1000** [comment]
You can still do that if youre host

**Comment by g0aty** [comment]
Anticheat got updated.
