### ISSUE TITLE
"allow player to noclip" patched

### ISSUE THREAD

**Issue by KidTechnical** [g0aty/SickoMenu#156]
Using "allow player to noclip" kicks you from the lobby immediately. Patched,

**Comment by KidTechnical** [comment]
Also "attempt to ban" bootkicks you from the lobby this worked yesterday

**Comment by KidTechnical** [comment]
And kill as crewmate everythings patched

**Comment by redphantom1000** [comment]
![image](https://github.com/user-attachments/assets/ba0168bd-81f4-419d-ac5b-a5a29cf9bebc)
from https://discord.gg/sickos

**Comment by redphantom1000** [comment]
Refer to what i said on the other issue i commented on
