### ISSUE TITLE
Cheats getting detected and kicking from game

### ISSUE THREAD

**Issue by Lorange7** [g0aty/SickoMenu#157]
Force roles mid game, kills using the menu and fake roles kick you from the game. Wallhacks and esp don't always work, reviving also crashes the game. i have tested this on public lobbys multiple times.

**Comment by redphantom1000** [comment]
Anticheat got updated
![Screenshot_20240906-121203](https://github.com/user-attachments/assets/e1488dd9-2c01-4d7a-b86f-6b259726a003)

**Comment by Lorange7** [comment]
> Anticheat got updated ![Screenshot_20240906-121203](https://private-user-images.githubusercontent.com/177276335/365235670-e1488dd9-2c01-4d7a-b86f-6b259726a003.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU2NjMzNDAsIm5iZiI6MTcyNTY2MzA0MCwicGF0aCI6Ii8xNzcyNzYzMzUvMzY1MjM1NjcwLWUxNDg4ZGQ5LTJjMDEtNGQ3YS1iODZmLTZiMjU5NzI2YTAwMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwNlQyMjUwNDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMzE5YTFkOGYzMTc2MDg0MDYyMWM5NDI2OWM2YzgxYWUzOTU3ZWI3YTUwODI4OThhNzI5NmQwOTQ3MDRjYjAxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Zs5wMtlUoze7q9eQG9foO-STWNofdtEaFcWV_F61zqQ)

is a workaround physically possible or will this permanently be broken?

**Comment by redphantom1000** [comment]
it has become a host only feature

**Comment by Lorange7** [comment]
even as host i get kicked and banned from the room

**Comment by g0aty** [comment]
Murder modules have been patched.
