### ISSUE TITLE
[ Bug ] FriendCodeFail, crash in practice.

### ISSUE THREAD

**Issue by glitchy-sk8k9** [g0aty/SickoMenu#161]
title, tell if need more info

**Comment by g0aty** [comment]
FriendCodeFail has nothing to do with the menu, practice mode crash is a duplicate issue and so this will be closed.

**Comment by glitchy-sk8k9** [comment]
> FriendCodeFail has nothing to do with the menu

Fixed by removing the menu actually.

**Comment by g0aty** [comment]
> > FriendCodeFail has nothing to do with the menu
> 
> Fixed by removing the menu actually.

Skill issue.
