### ISSUE TITLE
no games available

### ISSUE THREAD

**Issue by pep0w** [g0aty/SickoMenu#188]
with v4 no games are shown in the list, and it's also not possible to create one.

**Comment by RobloxGabriel1** [comment]
i think the lobby info feature is causing it. i tested a bunch of buttons to see which one is broken and the lobby info is one. im not a developer or anything like that, im just a person who downloaded this mod. for now, wait until they fix it.

**Comment by g0aty** [comment]
+25 causes this, works as intended.
