### ISSUE TITLE
bro how do i make myself imposter

### ISSUE THREAD

**Issue by s9rs** [g0aty/SickoMenu#197]

**Comment by katzklaw** [comment]
be host. that is the only way. smh

**Comment by s9rs** [comment]
What? Thats the only reason i got this mod, you know other mod menus that i can actually be imposter?

**Comment by YellowUi7** [comment]
> What? Thats the only reason i got this mod, you know other mod menus that i can actually be imposter?

It is not possible to become an imposter if you are not the owner of the lobby in Among Us

**Comment by katzklaw** [comment]
innersloth anticheat got updated end of september and again end of october and eliminated that feature.

**Comment by s9rs** [comment]
damn, thanks
