### ISSUE TITLE
abnormal number of impostors

### ISSUE THREAD

**Issue by TheFriSskx** [g0aty/SickoMenu#198]
when I start the game, there are 4 impostors in the game (in the previous version, 4.0, there were 3)

**Comment by fillwithjoy1** [comment]
@g0aty I figured out the problem

It appears that when starting the game, the menu adds impostors like this

Impostors (Total) = Base Impostors (if a lobby was 1/2/3 impostors) + Shapeshifters + Phantoms

Now here's the kicker, if you configured 9 phantoms in the roles settings for 3 impostors in a normal game will just increase the odds of getting Phantom. But the menu decides to add 9 extra impostors, who are just phantoms. It's very bizarre

Also crewmates spawn in as ghosts before getting their crewmate roles (aka STRMISS, "string missing" role which is the ghost role that Innersloth never coded in)

**Comment by g0aty** [comment]
Fixed!
