### ISSUE TITLE
Impostor count bug

### ISSUE THREAD

**Issue by bigdwag1** [g0aty/SickoMenu#201]
Whenever I host a lobby no matter if the custom imposter amount is enabled or disabled no matter what the settings are it is always 2 impostors. I am not very sure about why.

Also, a question I wanted to ask is for example cracked lobbies ones that I can turn off safe mode in?

**Comment by bigdwag1** [comment]
i think i might have found the solution
https://github.com/g0aty/SickoMenu/issues/198#issuecomment-2472258905

**Comment by JadenMcCallum** [comment]
Whats the soution because i'm also dealing with it

**Comment by g0aty** [comment]
Fixed!
