### ISSUE TITLE
Major Issues

### ISSUE THREAD

**Issue by 0Snake420** [g0aty/SickoMenu#211]
Imposter count no matter what when hosting is too high (4 to 5 imps when set to 3). Also there is some major glitches when not hosting and hosting with the phantom role turned on such as phantom killing, then being auto invisible after coming out a vent... Phantom killing, then phantom gets teleported to a random vent.

**Comment by 0Snake420** [comment]
Same thing happened here. I figured it may be part of my 0 kill cooldown setting where i modified code. So i deleted all the code, did a fresh reinstall. Still bugged...

**Comment by g0aty** [comment]
Fixed!
