### ISSUE TITLE
impostor roles

### ISSUE THREAD

**Issue by TheFriSskx** [g0aty/SickoMenu#216]
new bug, now impostors don't have role, phantom or shapeshifter, they are always basic impostors without role😭

**Comment by katzklaw** [comment]
huh. coulda swore it worked normally for me last night. i'll double check it to make sure.

**Comment by katzklaw** [comment]
tested. was getting only vanilla imp. did complete reinstall of the menu from fresh scratch clean among us install, and it works correctly now

**Comment by TheFriSskx** [comment]
> tested. was getting only vanilla imp. did complete reinstall of the menu from fresh scratch clean among us install, and it works correctly now

could you explain in more detail what you did? i reinstall among us, completely reinstalled the sicko menu and still the imposters are not given a role

**Comment by g0aty** [comment]
Fixed...
