### ISSUE TITLE
To many impostors

### ISSUE THREAD

**Issue by sudo-KitchenStove** [g0aty/SickoMenu#217]
When i host a game/get chosen to host (host left) it makes too many impostors

**example: i make myself impostor, and the regular imp amount is set to to, it chooses random imps twice and adds me in to the imps for a total of 5 imps in 1 round (the same with 1 and 3 regular imp amount)**

is this a **me** problem or **sickomenus** fault?

**Comment by katzklaw** [comment]
tested. if you add yourself as an impostor, it ADDS you to the impostors instead of assigning one of the impostor slots to you. you can only do this as host, so if you want to try to get away with this... reduce imp number by 1 and hope they don't notice

**Comment by g0aty** [comment]
Known issue, will be fixed in next update.

**Comment by g0aty** [comment]
Fixed!
