### ISSUE TITLE
Impersonation Issue (Bans you)

### ISSUE THREAD

**Issue by 0Snake420** [g0aty/SickoMenu#221]
Impersonation causes immediate ban even in safe mode.

**Comment by katzklaw** [comment]
can confirm. happened in my game a little bit ago

**Comment by Hackingisbad4** [comment]
> Impersonation causes immediate ban even in safe mode.

You deserve it, do not hack and ruin people games

**Comment by katzklaw** [comment]
lol someone's mad they got banned from the discord

**Comment by redphantom1000** [comment]
bruh

**Comment by 0Snake420** [comment]
Pep0w, ty I will try that!

**Comment by 0Snake420** [comment]
Btw this mod makes our games a much better experience. I don't use this mod at all to "ruin someone game" unless they try and ruin ours. I love that I am able to see when someone else is using a modded client and ban them immediately from our servers lobby. All of our friends love it too. And a lot of times my friends will ask me to "chang into them" as a joke. Well that's what happened, then I was banned for less than 10 secs (cause I know what I'm doing.)

**Comment by katzklaw** [comment]
i use this mod for similar harmless fun + banning troublemakers. my people love that they can share their favorite colors when i'm hosting. "can you magic me to (whatever color that's already taken) please?" is heard every night. last night we had 4 blacks and 3 blues.  it was the bruise crew. 🤣

**Comment by 0Snake420** [comment]
katzklaw that sounds like a lot of fun, I didn't even know you could the same color for more than one person, ty for letting me know that!

**Comment by 0Snake420** [comment]
@pep0w ty, **uninstalling and reinstalling everything** has worked to fix this.

**Comment by 0Snake420** [comment]
.

**Comment by 0Snake420** [comment]
I take it back guys sorry. I noticed only the first couple times I tried impersonation after a fresh reinstall did it work correctly. Its banning again in safe mode so I'm going to classify this as a bug now because you'd have to reinstall every time you wanna use.

Anyways here is some more bugs I noticed...

As phantom I am still again randomly teleported to a vent (at random so not every time I'm phantom)

The phantom glitch also causes me to appear invisible until the start of the next round.

Sometimes venting causes this to happen, and sometimes 2 phantoms (1 being you and 1 using their ability) will teleport you to them.

@g0aty

I only tagged cause I originally closed this as fixed, I know you're busy and will get to it when you can tho.

**Comment by g0aty** [comment]
Fixed in source code, getting teleported randomly to a vent seems to be a game glitch (although it is possible to execute it as host).

**Comment by g0aty** [comment]
Fixed!

**Comment by 0Snake420** [comment]
Thank you so much for all you do!
