### ISSUE TITLE
[Change Request] Try to keep the mark of the mod to a minimum

### ISSUE THREAD

**Issue by heavyutils** [g0aty/SickoMenu#23]
It takes the cleanliness of the game experience a bit away. Among Us Menu doesn't have the dev credits and mod version information filled everywhere. If anyone opens or uses the mod during streams they'll see the menu title too so you'll still have credit, you won't lose anything from it (assuming that's what you want). If the user would like to know the version, they can also just open the menu. No need to spam text everywhere.

Additionally, we can have an option to disable the ping counter altogether?

**Comment by g0aty** [comment]
The menu can be hidden from streaming applications (not now but in the update), but it has to be there to stop people leeching off of this menu and claiming it as their own.
As for the new feature, it has been planned for the update after the v3.4 release.

**Comment by heavyutils** [comment]
Suggestion then, you can include your name in the menu title bar. People r bound to open the menu to make any use of it.
