### ISSUE TITLE
Doesn't works with CrossOver (Mac Intel)

### ISSUE THREAD

**Issue by acer51-doctom** [g0aty/SickoMenu#233]
So the mod menu doesn't show up in Among Us, I put the Version.dll in the Among Us folder in `../steam/steamapps/common/Among Us/` and in the C Drive of the Bottle. I don't know why it does that since in a Parallels VM it works perfectly fine. I really don't know what to do now. I tried the Debug version and Release version.

**Comment by astra1dev** [comment]
You need to add a library override for version.dll. Not sure how this is done on Mac, but on Linux with Steam you set the launch arguments to `WINEDLLOVERRIDES="version=n,b" %command%`

**Comment by acer51-doctom** [comment]
Which library is it tho? I'm gonna try crtdll since there's a, well, "dll" in the name.

**Comment by astra1dev** [comment]
No, you need to add SickoMenu (version.dll) as library override

**Comment by acer51-doctom** [comment]
Found it lol, there like a ton of libraries and I didn't recognize any of them until (with more researching then quickly looking at it all) I found `version.dll`. Thanks for the help.

**Comment by astra1dev** [comment]
Thanks! If you want you can fork this repository, add instructions on how to get it working on Mac step-by-step, and then create a pull request. (We're still missing instructions for Mac as you can see in the README)

**Comment by acer51-doctom** [comment]
@astra1dev I'll gladly do this!

**Comment by acer51-doctom** [comment]
@VillainsRule I use Macked and Appstorrent lol
