### ISSUE TITLE
Shapesshifter

### ISSUE THREAD

**Issue by NightmareYTGM** [g0aty/SickoMenu#3]
When you transform into another crewmember and you kill and someone reports or activates the button and you are transformed, the effect is not deactivated and you continue transformed into another crewmember, that is when you are a shapeshifter. After the meeting is over, if you have little time, you will be untransformed in front of everyone.

**Comment by g0aty** [comment]
This is a known issue and will be patched in the next update!

**Comment by NightmareYTGM** [comment]
but I think there is one more, and that is when you go to turn on the lights, and you can't do it, IDK why.

**Comment by g0aty** [comment]
This issue's been patched, I'll release it in the update!

**Comment by g0aty** [comment]
fixed in v3.3.1

**Comment by heavyutils** [comment]
This issue is not fixed.
