### ISSUE TITLE
[Feature] All settings in Freeplay/Practice

### ISSUE THREAD

**Issue by heavyutils** [g0aty/SickoMenu#45]
An option in the menu to have ALL the hosting settings carry over to freeplay/practice, such as Emergency Meetings and Crewmate and Impostor Vision.

Only voting time and speed does for now afaik.

**Comment by g0aty** [comment]
Editing the host settings while in game is a planned feature!

**Comment by g0aty** [comment]
Duplicate of #22, so this will be closed. However, the feature is planned!
