### ISSUE TITLE
[Bug] "No ability cooldown" bugs

### ISSUE THREAD

**Issue by heavyutils** [g0aty/SickoMenu#50]
The cooldown timer for shift gets stuck at 1, the vent and protect buttons as engineer and guardian Angel respectively go invisible, and engineer vent button counts in negatives while in vent. Rarely, the shift button can also be invisible.

By the way, I would recommend using the GitHub labels for issues, it's way easier to handle than square bracket prefixes

**Comment by g0aty** [comment]
The buttons still work right? The invisible buttons are a game glitch, not a mod issue (afaik).
The custom tags are a great idea.

**Comment by heavyutils** [comment]
The buttons, yes, still work. I think this is only partially a game issue though. I think this can be fixed by setting the cooldown to 0.02s or something slightly above 0 with the No Ability Cooldown setting. Not sure, but it might work.

**Comment by g0aty** [comment]
Fixed!
