### ISSUE TITLE
Game not starting, version.dll faulty

### ISSUE THREAD

**Issue by NSTrains** [g0aty/SickoMenu#54]
Among us is not starting with the menu installed. Without the menu, Among us starts up. version.dll is faulty

**Comment by heavyutils** [comment]
Do you have any other mods such as BepInEx installed?

**Comment by NSTrains** [comment]
No I don't

**Comment by heavyutils** [comment]
Reinstall your Among us and try again

**Comment by heavyutils** [comment]
Also, try being patient first time you launch with this mod, it took 2 minutes for me first time

**Comment by g0aty** [comment]
I've figured out a patch for this, it'll be fixed next update!

**Comment by RobloxGabriel1** [comment]
whenever you insert a mod in among us, you need to be patient so that it installs it and loads among us with it
