### ISSUE TITLE
Issue #15 is still a problem (with potential solution)

### ISSUE THREAD

**Issue by heavyutils** [g0aty/SickoMenu#55]
The game still ends when as impostor you press the emergency button. #15

I used shapeshifter to test in a local hosted game with only me, but it's probably the same with normal imposter.

This also happens when switching during the meeting.

EDIT: I think I found out the issue. Is that the crew gets a task win because there are no crews with incomplete tasks left. That's just what I think though. You can try it out by trying to make it disable tasks win if you haven't already.

**Comment by g0aty** [comment]
Great idea, I probably forgot to check for that.
