### ISSUE TITLE
When I press the Delete button, the menu does not appear.

### ISSUE THREAD

**Issue by Terrerbite** [g0aty/SickoMenu#59]
As the title suggests, the logo is popping up in the bottom window, and it has loaded successfully, but the menu does not appear. (In addition, the Insert button does not appear when entered.)

**Comment by Terrerbite** [comment]
[12:52:09] [DEBUG - UNITY] GET account deletion info 404 Could this have something to do with what happened to me?

**Comment by g0aty** [comment]
Press the delete key on your keyboard. Your keyboard doesn't have a delete key? Google "how to press delete on <your keyboard's name>". Or change the keybind in sicko-settings.json which can be found in your Among Us directory, valid keybind values can be found here: https://learn.microsoft.com/en-us/windows/win32/inputdev/virtual-key-codes

The account deletion info 404 is just a Unity log telling you that your account deletion info doesn't exist, and it has nothing to do with the menu but a Unity log that shows up by default on login.

**Comment by heavyutils** [comment]
> As the title suggests, the logo is popping up in the bottom window, and it has loaded successfully, but the menu does not appear. (In addition, the Insert button does not appear when entered.)

The menu opens up when you start among us, change keybinds there then
