### ISSUE TITLE
How do I open the menu

### ISSUE THREAD

**Issue by KidTechnical** [g0aty/SickoMenu#6]
Title says it all.
Probably a stupid question lmao

**Comment by g0aty** [comment]
Press the delete key to open the menu, or if you can't press delete, go to your among us directory, open "sicko-settings.json", and change the keybinds for "Toggle_Menu" to the number of the corresponding key you can actually press: https://boostrobotics.eu/windows-key-codes/ contains a list of keys along with their keycodes!
