### ISSUE TITLE
[Bug] SickoMenu is incompatible with new version of Among Us.

### ISSUE THREAD

**Issue by stretch07** [g0aty/SickoMenu#60]
SickoMenu causes the game to crash before the loading screen because it's incompatible with the new version of AU.
@g0aty could you please publish a new version possibly

**Comment by vofq** [comment]
It works for me (I do use epic games)

**Comment by heavyutils** [comment]
> SickoMenu causes the game to crash before the loading screen because it's incompatible with the new version of AU.
> 
> @g0aty could you please publish a new version possibly

This happens for me 1/10 of the times it's not that bad
