### ISSUE TITLE
Question!

### ISSUE THREAD

**Issue by sm0ke1337** [g0aty/SickoMenu#61]
First of all good job this menu is the best 1 for this game.

I want to ask you how did you bypass the Kill Cooldown and if it's possible to do it external with cheat engine for example.

**Comment by g0aty** [comment]
Keep setting the local player's kill cooldown to zero, and modify all CmdCheckMurder packets to be sent as RpcMurderPlayer packets.

**Comment by sm0ke1337** [comment]
thank you vey much brother keep up the great job!!!!!
