### ISSUE TITLE
Chat as others and kill as others without kick

### ISSUE THREAD

**Issue by heavyutils** [g0aty/SickoMenu#63]
Make an optional setting (or just make it default when Safe Mode is on) that turns yiu into the other player name, color, and cosmetics temporarily just to send a message, do the kill, etc. before turning back. This can evade the kick. The option should also turn you into shapeshifter for a short while when shifting with safe mode. I've tested this by manually changing color and role and it works.

**Comment by g0aty** [comment]
Chat messages show the sender with your outfit after closing and reopening chat, while killing might reveal you because the kill animation shows your outfit at the time when the animation starts.
