### ISSUE TITLE
Vent time limit is always 1s in Hide n Seek

### ISSUE THREAD

**Issue by heavyutils** [g0aty/SickoMenu#66]
No matter the settings

**Comment by g0aty** [comment]
Interesting, I might need a more detailed explanation of what happens.

**Comment by heavyutils** [comment]
Ik the menu died, but when I mcrewmate and enter the vent in hide n seek, I get kicked out of it after 1 second, no matter how long in the game settings the vent duration is

**Comment by RobloxGabriel1** [comment]
If the menu isn't working in Among Us due to the major update. You need to remove the mods. Or turn off Disable vents if the mod is warking.

**Comment by g0aty** [comment]
I believe this has been patched.
