### ISSUE TITLE
New Update, menu doesn't work.

### ISSUE THREAD

**Issue by WhisperAqual** [g0aty/SickoMenu#68]
(you are most likely aware) but Among Us released an update at Nintendo Direct so the menu doesn't appear.

**Comment by lephiz69** [comment]
damn bro what did you expect when new update releases with 3 new roles and a bunch of fixes?

**Comment by heavyutils** [comment]
> damn bro what did you expect when new update releases with 3 new roles and a bunch of fixes?

It has worked before? This was probably just because they changed a little more than usual and added more roles. No need to be rude about it.

**Comment by WhisperAqual** [comment]
yeah im saying it usually happens every major update

**Comment by HasanTheGlitcher** [comment]
same

**Comment by g0aty** [comment]
This is a major update, and a lot of stuff has broken. Expect a hotfix in the next few days.

**Comment by WhisperAqual** [comment]
every time im crew im bouta become noisemaker (you can have all the other abilities with the menu)
