### ISSUE TITLE
Make EGS: Supported to EGS: Works Sometimes

### ISSUE THREAD

**Issue by WayloFunk** [g0aty/SickoMenu#70]
EGS version of Among Us (From what I heard) 90% of the time works

**Comment by heavyutils** [comment]
What is eggs?

**Comment by WayloFunk** [comment]
Epic Games Store

**Comment by heavyutils** [comment]
It's already supported

**Comment by WayloFunk** [comment]
I know but, I hear people have trouble with EGS
