### ISSUE TITLE
New update and 3 roles come menu not working

### ISSUE THREAD

**Issue by HasanTheGlitcher** [g0aty/SickoMenu#71]
Sİnce the new tracker, noisemaker, phantom roles update come, The menu doesnt work, I has been waiting for 1 days and still its not fixed,

**Comment by heavyutils** [comment]
We are all experiencing that issue

**Comment by heavyutils** [comment]
Just wait a little a hotfix will probably come

**Comment by HasanTheGlitcher** [comment]
@heavyutils i didnt think someone would reply that fast, ok then i will wait, thanks for replying.
(btw im someone who is rarely busy and anyone can get reply from me without waiting much)

**Comment by heavyutils** [comment]
> bruh im still waiting

If only it took minutes. I think it'll take anywhere within 3 to 7 days from now for a hotfix. I'm not the creator; this is just my guess. The menu will likely get a few updates following.

**Comment by g0aty** [comment]
Duplicate of #68
