### ISSUE TITLE
OH NO THE UPDATE

### ISSUE THREAD

**Issue by sebi96test** [g0aty/SickoMenu#75]
They've made a new update, it won't inject.

**Comment by Zexylz** [comment]
so you should ike update it sebi96test

**Comment by WayloFunk** [comment]
#68 of Duplicate

**Comment by heavyutils** [comment]
> #68 of Duplicate

It's not buddy

**Comment by heavyutils** [comment]
> They've made a new update, it won't inject.

He didn't upload the release yet, only the code (the code doesn't fully work)
