### ISSUE TITLE
I have 3 feature ideas

### ISSUE THREAD

**Issue by CyanTheCyantist** [g0aty/SickoMenu#76]
Im not sure if this is possible anymore, but I think there should be a feature to change your player ID to just mess with people with your pitch in chat

Again, im not sure if this is possible anymore, but I think there should be a feature to spawn and despawn stuff (examples are spawning the skeld and despawning the dropship)

Like the other 2, im not sure if it can be done now, but I think you should be able to put custom settings (examples are 0 kill cooldown, 1s meetings, spam vent as engineer, spam guardian angel, spam shapeshifter)

**Comment by heavyutils** [comment]
I took a look in the among us assets and it definitely is possible to load and unload rooms

**Comment by g0aty** [comment]
Feature 2 could be possible, feature 3 already exists, but feature 1 is impossible!

**Comment by usor-usor** [comment]
> ure if this is possible anymore, but I think there should be a feature to change your player ID to just mess with people with your pitch in chat

it is possible u just need a new steam account with amongus ore it ore make an ew steam account and download amongus on it
