### ISSUE TITLE
[Major bug] Local does not work

### ISSUE THREAD

**Issue by heavyutils** [g0aty/SickoMenu#78]
My game crashes when I try to host. Both with and without internet.

**Comment by kalik414** [comment]
same thing

**Comment by g0aty** [comment]
Thanks, it'll be fixed next update!

**Comment by heavyutils** [comment]
> Thanks, it'll be fixed next update!

It never got fixed :(

**Comment by RobloxGabriel1** [comment]
it works for me???

**Comment by heavyutils** [comment]
> it works for me???
> 
> 

erm how

**Comment by 534544444lolf** [comment]
how do you even open the menu?? I downloaded 3.5.2 today and it wont open? Is it because I haev a 60% keyboard? I also cant find "sicko-settings.json" help please

**Comment by terrifyiedz** [comment]
If it doesn't automatically open, press the "delete" key, if you don't see any of the sicko files or folder in the among us game files, redownload the v3.5.2 release.zip and do the setup again

**Comment by heavyutils** [comment]
did this get fixed in 3.6?

**Comment by MachinePlaygroundPeopleMachine** [comment]
> did this get fixed in 3.6?

Does the version dll for 3.6 work because it's not working for me. The server list is empty, no servers are being shown and the menu doesn't open when pressing del.

**Comment by heavyutils** [comment]
Version.dll doesn't work.

**Comment by MachinePlaygroundPeopleMachine** [comment]
> Version.dll doesn't work.

I kind of figured

**Comment by g0aty** [comment]
Fixed!
