### ISSUE TITLE
Host crash

### ISSUE THREAD

**Issue by Volka11636** [g0aty/SickoMenu#89]
![image](https://github.com/g0aty/SickoMenu/assets/79438701/02e68b6d-fabc-4ad8-a898-caf06dc1990a)
it's opening if tou click on host button

**Comment by Loyzi** [comment]
Known error, please wait for a fix

**Comment by RobloxGabriel1** [comment]
g0aty said that this was a rushed release so there are bugs. its a known bug so you have to wait for sickomenu 3.6 or 4.0 to come out.
