### ISSUE TITLE
dosent save

### ISSUE THREAD

**Issue by SubnauticaLaserMain** [g0aty/SickoMenu#91]
when i try to save, it dosen't save, when i load back into among us, the 'save file' dosent seem to load, or dosen't save, idk, but, it dosen't wanna save

**Comment by Corvex2** [comment]
same

**Comment by RobloxGabriel1** [comment]
when you choose the choices you like, you need to save your config. the next time you open up among us, sickomenu will load that config.

**Comment by SubnauticaLaserMain** [comment]
i tried to do a force-save and force-load, it didnt work
