### ISSUE TITLE
download

### ISSUE THREAD

**Issue by modder780** [g0aty/SickoMenu#92]
how to download mod/cheat menu when i do a build theirs 1 error something about echo

**Comment by WayloFunk** [comment]
Get git cmd and run in command prompt: git clone https://github.com/g0aty/SickoMenu/

**Comment by WayloFunk** [comment]
Then you open the project in C:/users/yourname/SickoMenu

**Comment by WayloFunk** [comment]
I forgot to mention you can’t just manually download the zip

**Comment by heavyutils** [comment]
> I forgot to mention you can’t just manually download the zip

Wdym? I did that and it works perfectly fine.

**Comment by heavyutils** [comment]
Just downlaod zip, extract it, open in VS. it's that easy
