### ISSUE TITLE
dude menu is broken

### ISSUE THREAD

**Issue by heavyutils** [g0aty/SickoMenu#98]
the menu is still nonfunctional it crashes upon entering the game

**Comment by terrifyiedz** [comment]
Remove DirectX overlays, once removed if the menu doesnt show in-game press the "delete" , and it should pop up.

**Comment by heavyutils** [comment]
That isn't the issue, it crashes when I try to load up a lobby

**Comment by terrifyiedz** [comment]
Oh I thank you're talking about the host tab, goats working on that right for know use the other features I suggest not hosting ti'll a fix is released

**Comment by RobloxGabriel1** [comment]
I have the same issue. I uploaded it called "Host Start Glitch."

**Comment by RobloxGabriel1** [comment]
For now I just use the host abilities in the lobby until it's fixed.
